version: '3.3'

# Define services
services:
  # testing:
  #   working_dir: /app
  #   image: golang:1.21
  #   ports:
  #     - "9205:9205"
  #   tty: true
  #   container_name: fuzzy_testing
  #   volumes: 
  #     - ./:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=fuzzy #also the default db
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  # App Service
  user-api:
    container_name: fuzzy-user-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9205:9205" 
    restart: unless-stopped
    # environment: 
    #   REDIS_URL: redis:6379
    # networks: 
    #   - backend
volumes:
  db:
    driver: local

