version: '3.3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: database
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  user-api:   
    container_name: fuzzy-user-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9205:9205" 
    restart: unless-stopped
    env_file:
      - dev.env
  # testing:
  #   working_dir: /app
  #   image: golang:1.21
  #   ports:
  #     - "9205:9205"
  #   tty: true
  #   container_name: fuzzy_testing
  #   volumes: 
  #     - ./:/app
  #   env_file:
  #     - dev.env
volumes:
  db:
    driver: local

